/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './modules/__root'
import { Route as IndexRouteImport } from './modules/index'
import { Route as EwarsForecastsAlertsIndexRouteImport } from './modules/ewars-forecasts-alerts/index'
import { Route as CurrentMalariaSituationIndexRouteImport } from './modules/current-malaria-situation/index'
import { Route as ClimateMalariaRelationshipIndexRouteImport } from './modules/climate-malaria-relationship/index'
import { Route as ChapThresholdIndexRouteImport } from './modules/chap-threshold/index'
import { Route as ChapForecastAlertsIndexRouteImport } from './modules/chap-forecast-alerts/index'
import { Route as ChapEvaluationIndexRouteImport } from './modules/chap-evaluation/index'
import { Route as ChapCompareIndexRouteImport } from './modules/chap-compare/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EwarsForecastsAlertsIndexRoute =
  EwarsForecastsAlertsIndexRouteImport.update({
    id: '/ewars-forecasts-alerts/',
    path: '/ewars-forecasts-alerts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurrentMalariaSituationIndexRoute =
  CurrentMalariaSituationIndexRouteImport.update({
    id: '/current-malaria-situation/',
    path: '/current-malaria-situation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClimateMalariaRelationshipIndexRoute =
  ClimateMalariaRelationshipIndexRouteImport.update({
    id: '/climate-malaria-relationship/',
    path: '/climate-malaria-relationship/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChapThresholdIndexRoute = ChapThresholdIndexRouteImport.update({
  id: '/chap-threshold/',
  path: '/chap-threshold/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapForecastAlertsIndexRoute = ChapForecastAlertsIndexRouteImport.update({
  id: '/chap-forecast-alerts/',
  path: '/chap-forecast-alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapEvaluationIndexRoute = ChapEvaluationIndexRouteImport.update({
  id: '/chap-evaluation/',
  path: '/chap-evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapCompareIndexRoute = ChapCompareIndexRouteImport.update({
  id: '/chap-compare/',
  path: '/chap-compare/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chap-compare/': typeof ChapCompareIndexRoute
  '/chap-evaluation/': typeof ChapEvaluationIndexRoute
  '/chap-forecast-alerts/': typeof ChapForecastAlertsIndexRoute
  '/chap-threshold/': typeof ChapThresholdIndexRoute
  '/climate-malaria-relationship/': typeof ClimateMalariaRelationshipIndexRoute
  '/current-malaria-situation/': typeof CurrentMalariaSituationIndexRoute
  '/ewars-forecasts-alerts/': typeof EwarsForecastsAlertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chap-compare': typeof ChapCompareIndexRoute
  '/chap-evaluation': typeof ChapEvaluationIndexRoute
  '/chap-forecast-alerts': typeof ChapForecastAlertsIndexRoute
  '/chap-threshold': typeof ChapThresholdIndexRoute
  '/climate-malaria-relationship': typeof ClimateMalariaRelationshipIndexRoute
  '/current-malaria-situation': typeof CurrentMalariaSituationIndexRoute
  '/ewars-forecasts-alerts': typeof EwarsForecastsAlertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chap-compare/': typeof ChapCompareIndexRoute
  '/chap-evaluation/': typeof ChapEvaluationIndexRoute
  '/chap-forecast-alerts/': typeof ChapForecastAlertsIndexRoute
  '/chap-threshold/': typeof ChapThresholdIndexRoute
  '/climate-malaria-relationship/': typeof ClimateMalariaRelationshipIndexRoute
  '/current-malaria-situation/': typeof CurrentMalariaSituationIndexRoute
  '/ewars-forecasts-alerts/': typeof EwarsForecastsAlertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chap-compare/'
    | '/chap-evaluation/'
    | '/chap-forecast-alerts/'
    | '/chap-threshold/'
    | '/climate-malaria-relationship/'
    | '/current-malaria-situation/'
    | '/ewars-forecasts-alerts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chap-compare'
    | '/chap-evaluation'
    | '/chap-forecast-alerts'
    | '/chap-threshold'
    | '/climate-malaria-relationship'
    | '/current-malaria-situation'
    | '/ewars-forecasts-alerts'
  id:
    | '__root__'
    | '/'
    | '/chap-compare/'
    | '/chap-evaluation/'
    | '/chap-forecast-alerts/'
    | '/chap-threshold/'
    | '/climate-malaria-relationship/'
    | '/current-malaria-situation/'
    | '/ewars-forecasts-alerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChapCompareIndexRoute: typeof ChapCompareIndexRoute
  ChapEvaluationIndexRoute: typeof ChapEvaluationIndexRoute
  ChapForecastAlertsIndexRoute: typeof ChapForecastAlertsIndexRoute
  ChapThresholdIndexRoute: typeof ChapThresholdIndexRoute
  ClimateMalariaRelationshipIndexRoute: typeof ClimateMalariaRelationshipIndexRoute
  CurrentMalariaSituationIndexRoute: typeof CurrentMalariaSituationIndexRoute
  EwarsForecastsAlertsIndexRoute: typeof EwarsForecastsAlertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ewars-forecasts-alerts/': {
      id: '/ewars-forecasts-alerts/'
      path: '/ewars-forecasts-alerts'
      fullPath: '/ewars-forecasts-alerts/'
      preLoaderRoute: typeof EwarsForecastsAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-malaria-situation/': {
      id: '/current-malaria-situation/'
      path: '/current-malaria-situation'
      fullPath: '/current-malaria-situation/'
      preLoaderRoute: typeof CurrentMalariaSituationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate-malaria-relationship/': {
      id: '/climate-malaria-relationship/'
      path: '/climate-malaria-relationship'
      fullPath: '/climate-malaria-relationship/'
      preLoaderRoute: typeof ClimateMalariaRelationshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chap-threshold/': {
      id: '/chap-threshold/'
      path: '/chap-threshold'
      fullPath: '/chap-threshold/'
      preLoaderRoute: typeof ChapThresholdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chap-forecast-alerts/': {
      id: '/chap-forecast-alerts/'
      path: '/chap-forecast-alerts'
      fullPath: '/chap-forecast-alerts/'
      preLoaderRoute: typeof ChapForecastAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chap-evaluation/': {
      id: '/chap-evaluation/'
      path: '/chap-evaluation'
      fullPath: '/chap-evaluation/'
      preLoaderRoute: typeof ChapEvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chap-compare/': {
      id: '/chap-compare/'
      path: '/chap-compare'
      fullPath: '/chap-compare/'
      preLoaderRoute: typeof ChapCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChapCompareIndexRoute: ChapCompareIndexRoute,
  ChapEvaluationIndexRoute: ChapEvaluationIndexRoute,
  ChapForecastAlertsIndexRoute: ChapForecastAlertsIndexRoute,
  ChapThresholdIndexRoute: ChapThresholdIndexRoute,
  ClimateMalariaRelationshipIndexRoute: ClimateMalariaRelationshipIndexRoute,
  CurrentMalariaSituationIndexRoute: CurrentMalariaSituationIndexRoute,
  EwarsForecastsAlertsIndexRoute: EwarsForecastsAlertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
